### ISSUE TITLE
Make PaymentMethodTypes configurable

### ISSUE THREAD

**Issue by mattbrailsford** [vendrhub/vendr-payment-provider-stripe#6]
Currently, the PaymentMethodTypes setting of the Stripe Session object is hard coded to be "card" however there are multiple other supported payment method types that people may wish to use such as banconnect (https://stripe.com/docs/payments/bancontact/accept-a-payment). We should make this setting configurable so that implementers can make use of those additional payment options.

I think this can be pretty easily done by making this a stripe payment provider setting (probably in the advanced section) that just accepts a coma separated list of payment method types to use.

**Comment by bjarnef** [comment]
It could be something like this as in Reepay:
https://github.com/vendrcontrib/vendr-payment-provider-reepay/blob/dev/src/Vendr.Contrib.PaymentProviders.Reepay/ReepayCheckoutPaymentProvider.cs#L54-L57

Some payment gateway allow to add `!` (not) operator in front to disallow/blacklist this. Others like Adyen has separate properties to handle this: https://github.com/vendrcontrib/vendr-payment-provider-adyen/blob/dev/src/Vendr.Contrib.PaymentProviders.Adyen/AdyenCheckoutPaymentProvider.cs#L100-L108

**Comment by bjarnef** [comment]
@mattbrailsford it seems you have worked on this here https://github.com/vendrhub/vendr-payment-provider-stripe/commit/c0c78f4a59b28d1db0c767ce805f29291a6d8517

Not sure how Stripe handle this, but some payment gateways just use the account specific payment methods if empty in the request - sometimes just all payment methods available, sometimes it is possible to configurate "default" payment method in the account.

It probably also depends on if the property is required or optional in the payment request.

**Comment by mattbrailsford** [comment]
According to the docs, this is the description of that field:

> The list of payment method types that this PaymentIntent is allowed to use. If this is not provided, defaults to [“card”]. Valid payment method types include: alipay, au_becs_debit, bacs_debit, bancontact, card, card_present, eps, giropay, ideal, interac_present, p24, sepa_debit, and sofort.

As such I don't think leaving it blank will default to some "portal specific configuration" so I'm fine with what it's doing for now. This will be out in a new patch release soon. Just having to do some updates around the subscriptions stuff.

**Comment by bjarnef** [comment]
Yes, in this for Stripe it seems it would be the same as in code (unless Stripe changed the default someday).
I just tend to leave it empty unless it is required and not something specified in the settings property 😁

It shouldn't be a big deal though as you can specify the payment methods in the property in Vendr 💳

**Comment by mattbrailsford** [comment]
Fixed in 1.2.1 which was released today
