### ISSUE TITLE
Refund action not working

### ISSUE THREAD

**Issue by michelebenolli** [vendrhub/vendr-payment-provider-stripe#8]
The “Refund” button on the order detail page is not working. 
When I generate a refund from the Stripe panel (dashboard.stripe.com), the payment status is changed and the information is correctly fetched and displayed by Vendr in the order detail’s view.
However, when I click the button and confirm the choice, the following message shows up: “Payment Refunded: Captured payment successfully refunded”. Despite the success message, the refund is not generated and the payment status remains unaltered.
[Vendr v1.8.4-beta0001 and Stripe v1.2.1]

**Comment by mattbrailsford** [comment]
Hi @michelebenolli 

Just fixed this locally now, should be a new beta build on the unstable feed in a few minutes. Let me know if this fixes things for you.

Matt

**Comment by michelebenolli** [comment]
This issue is fixed in Vendr v1.8.4-beta0002, thank you!
